### ISSUE TITLE
All maps load failed

### ISSUE THREAD

**Issue by ruth3n** [KuromeSama6/Autosu#1]
All maps wors normally in osu! but failed to load in autosu!.
![image](https://github.com/KuromeSama6/Autosu/assets/108727970/6cbaf43d-46ca-4d8b-bcab-fa12d6e4a381)

**Comment by KuromeSama6** [comment]
Please provide a link to said beatmaps and I'll look into it.

**Comment by KuromeSama6** [comment]
No further details provided. Closing.
